name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

      - name: Install NPM
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env: 
          APP_URL: "http://localhost:3000"
          NEXT_PUBLIC_API_BASE_URL: "https://devstore-api-gamma-mauve.vercel.app/"
        with:
          build: npm run build
          start: npm start